config/routes.rb
DoRubyTuesday::Application.routes.draw do
  resources :testimonials

	get "store/show"
	get "help_wanted/show"
  get "contact/show"
	get "auth/index"
	get "auth/callback"
	get "auth/logout"
	get "unauthorized/unauthorized"

	root :to => "welcome#index"

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :name
	attr_accessor :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/auth_controller.rb
require 'net/http'

class AuthController < ApplicationController
	def initialize
		if @client.nil?
			@client = TwitterOAuth::Client.new( 
				:consumer_key => 'TFzFh0qEhFGjA5uHWAJBCQ',
				:consumer_secret => 'vxegxZn5AeZ3Tzl5NaMz4LsulAkFLH0BlIjo9vjkEEU' 
			)
		end
	end

	def index
		request_token = @client.request_token(
			:oauth_callback => url_for(:controller => 'auth', :action => 'callback')
		)
		session[:request_token] = request_token.token
		session[:request_token_secret] = request_token.secret
		redirect_to request_token.authorize_url.gsub('authorize', 'authenticate')
	end

	def callback
		@access_token = @client.authorize(
			session[:request_token],
			session[:request_token_secret],
			:oauth_verifier => params[:oauth_verifier]	
		)

		if @client.authorized?
			session[:access_token] = @access_token.token
			session[:secret_token] = @access_token.secret
			session[:user] = create_user_from_twitter(@client)
			redirect_to '/'
		else
			redirect_to 'failed'
		end
	end

	def logout
		session[:user] = nil
		redirect_to '/'
	end

private
	def create_user_from_twitter(client)
		user = User.new
		user.name = client.info["screen_name"]
		user.profile_image = client.info["profile_image_url"]
		user
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
    render "show", :layout => true
  end

end

app/controllers/help_wanted_controller.rb
class HelpWantedController < ApplicationController
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
end

app/controllers/testimonial_controller.rb
class TestimonialController < ApplicationController
	def show
    render "show", :layout => true
	end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonials
  # GET /testimonials.xml
  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.xml
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.xml
  def new
		if session[:user].nil?
			redirect_to :controller => 'unauthorized', :action => 'unauthorized'
			return
		end
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.xml
  def create
    @testimonial = Testimonial.new(params[:testimonial])

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to(@testimonial, :notice => 'Testimonial was successfully created.') }
        format.xml  { render :xml => @testimonial, :status => :created, :location => @testimonial }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @testimonial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /testimonials/1
  # PUT /testimonials/1.xml
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(params[:testimonial])
        format.html { redirect_to(@testimonial, :notice => 'Testimonial was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @testimonial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.xml
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to(testimonials_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/unauthorized_controller.rb
class UnauthorizedController < ApplicationController
	def index
		render "unauthorized"
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@user = session[:user]
		render "index", :layout => true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/help_wanted_helper.rb
module HelpWantedHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/testimonial_helper.rb
module TestimonialHelper
	def twitter_oauth_url
		@consumer=OAuth::Consumer.new( "TFzFh0qEhFGjA5uHWAJBCQ","vxegxZn5AeZ3Tzl5NaMz4LsulAkFLH0BlIjo9vjkEEU", {
			:site=>"https://agree2"
		})

		@request_token=@consumer.get_request_token
		session[:request_token]=@request_token
		@request_token.authorize_url
	end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/unauthorized_helper.rb
module UnauthorizedHelper
end

app/views/contact/show.html.erb
<h1>Contact us!</h1>

<h2>About us</h2>
<p>We're just a couple of guys who wanted an excuse to do some ruby every week (or more). Tuesday seemed
like the easiest way to remember, and what better project could we pick than one to encourage people to join us?
</p>
<p>
Feel free to contact us on twitter if you'd like to get to know us better
</p>

<h2>Twitter</h2>
<ul>
	<li>@kbaribeau</li>
	<li>@78mgb</li>
</ul>


<%= link_to "Go Home", "/" %>

app/views/help_wanted/show.erb
<h1>Help Wanted!</h1>

<h2>Hey! We need help!</h2>
	<p> We're looking to expand the site, feel free to 
		<a href="https://github.com/kbaribeau/do_ruby_tuesday">fork the github repo</a>
		and add whatever you like, but we're especially interested in the following
	</p>
<ul>
	<li>Make it look more awesome</li>
	<li>Improve the dev environment (for the record, we think rspec's is super-cool)</li>
	<li>work on something random from <a href="https://www.pivotaltracker.com/projects/134874">the backlog</a></li>
</ul>

<%= link_to "Go Home", "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>DoRubyTuesday</title>
		<%= stylesheet_link_tag :all %>
		<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js" %>
		<%= javascript_include_tag "/javascripts/raptorize/jquery.raptorize.1.0.js" %>
		<%= csrf_meta_tag %>
		<meta http-equiv="X-UA-Compatible" content="chrome=1">

		<script type="text/javascript">
			$(function() {
				$('body').raptorize({
						'enterOn': 'konami-code'	
					});
			});

		</script>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/store/show.erb
<h1>Store!</h1>

<h2>Coming Soon!</h2>
<p>Our plan is to sell little flags that say Ruby Tuesday! You can bring them to your local cofee shop,
put them up while your working, and everyone will know your working on ruby, and are happy to hang out
with anyone else who might be interested.</p>

<%= link_to "Go Home", "/" %>

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<h1>Testimonials</h1>

<h2>Coming Soon!</h2>
<p>We're looking for testimonials!  If you want to say something like "Doing ruby is always better on a Tuesday!",
or "I love Ruby, especially on Tuesdays!", <%= link_to "drop us a line", contact_show_path %>, and we'll put your name and quote up here.</p>

<p>Also, don't forget to tweet with the #dorubytuesday hashtag!</p>


<table>
  <tr>
    <th>Name</th>
    <th>Quote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testimonials.each do |testimonial| %>
  <tr>
    <td><%= testimonial.name %></td>
    <td><%= testimonial.quote %></td>
    <td><%= link_to 'Show', testimonial %></td>
    <td><%= link_to 'Edit', edit_testimonial_path(testimonial) %></td>
    <td><%= link_to 'Destroy', testimonial, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "New Testimonial", new_testimonial_path %>
<%= link_to "Go Home", "/" %>

<%= link_to('sign in', :controller => 'auth', :action => 'index') %>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimonial.name %>
</p>

<p>
  <b>Quote:</b>
  <%= @testimonial.quote %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>

app/views/unauthorized/unauthorized.erb
<html>
	<head></head>
	<body>
		<h1>You shall not pass!</h1>
		<p>You're not allowed to visit this page, go away.</p>
	</body>
</html>

app/views/welcome/index.erb
<div id="forkme-banner">
	<a href="http://github.com/kbaribeau/do_ruby_tuesday">
		<img style="position: absolute; top: 0; right: 0; border: 0;" src="https://assets1.github.com/img/e6bef7a091f5f3138b8cd40bc3e114258dd68ddf?repo=&url=http%3A%2F%2Fs3.amazonaws.com%2Fgithub%2Fribbons%2Fforkme_right_red_aa0000.png&path=" alt="Fork me on GitHub">
	</a>
</div>

<div id="welcome">
	<div id="header">
		<img id="logo" src="/images/ruby_tuesday.png" />
	</div>

	<div id="menu-row">
		<span class="menu-item"><%= link_to "Store", store_show_path, :class => 'menu-item' %></span>
		<span class="menu-sep">|</span>
		<span class="menu-item"><%= link_to "Help Wanted", help_wanted_show_path, :class => 'menu-item' %></span>
		<span class="menu-sep">|</span>
		<span class="menu-item"><%= link_to "Testimonials", testimonials_path, :class => 'menu-item' %></span>
		<span class="menu-sep">|</span>
		<span class="menu-item"><%= link_to "Contact", contact_show_path, :class => 'menu-item' %></span>
	</div>

	<div id="content">
		<div id="rulesOfEngagement">
			<table cellspacing="10">
				<tr>
					<th>Venue</th>
					<th>City</th>
					<th>State</th>
					<th>Reps</th>
				</tr>
				<tr>
					<td>Main Street Coffee House</td>
					<td>South Bend</td>
					<td>Indiana</td>
					<td>
						<a href="http://twitter.com/78mgb">@78mgb</a>, 
						<a href="http://twitter.com/kbaribeau">@kbaribeau</a>
					</td>
				</tr>
				<tr>
					<td>On @bostonaholic&apos;s Couch</td>
					<td>Columbus</td>
					<td>Ohio</td>
					<td><a href="http://twitter.com/bostonaholic">@bostonaholic</a></td>
				</tr>
				<tr>
					<td>A Pillar Code Dojo</td>
					<td>Ann Arbor</td>
					<td>Michigan</td>
					<td><a href="http://twitter.com/crebma">@crebma</a></td>
				</tr>
			</table>
		</div>
		<div id="doRubyTuesdayVenues">
			<div id="rules">
				<h2>Rules of Engagement</h2>
				<ul>
					<li>Meet at a locally owned venue</li>
					<li>Plant your pennant!</li>
					<li>Do Ruby!</li>
					<li>Tweet about it #dorubytuesday</li>
				</ul>
			</div>
			<div id="twitterFall">
				<script src="http://widgets.twimg.com/j/2/widget.js"></script>
				<script>
				new TWTR.Widget({
					version: 2,
					type: 'search',
					search: '#dorubytuesday',
					interval: 4000,
					title: 'Ruby Tuesday!',
					subject: 'ROMG!',
					width: 250,
					height: 300,
					theme: {
						shell: {
							background: '#b22222',
							color: '#ffffff'
						},
						tweets: {
							background: '#ffffff',
							color: '#444444',
							links: '#000000'
						}
					},
					features: {
						scrollbar: false,
						loop: true,
						live: true,
						hashtags: true,
						timestamp: true,
						avatars: true,
						toptweets: true,
						behavior: 'default'
					}
				}).render().start();
				</script>
			</div>
		</div>
	</div>
</div>